[project]
name = "landscape-client-charm"
version = "0.1.0"
description = "Juju charm for installing Landscape Client"
requires-python = ">=3.8"
dependencies = [
    "ops>=1.5.0",
]

[dependency-groups]
dev = [
    "codespell",
    "coverage[toml]",
    "pytest",
    "ruff",
]
integration = [
    "juju",
    "pytest-operator",
    "pyyaml",
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.ruff]
line-length = 99
target-version = "py38"
extend-exclude = ["lib"]

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
ignore = [
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "Q004",
    "COM812",
    "COM819",
    "ISC002",
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
order-by-type = false
case-sensitive = false

[tool.pytest.ini_options]
log_cli_level = "INFO"
pythonpath = [".", "lib", "src"]
testpaths = ["tests"]
