name: Lint charm

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    if: "!github.event.pull_request.draft"
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Check linting and formatting
        run: make check
